name: my-workflow
jobs:
  bun-check:
    name: bun-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun install
      - run: bun lint
      - run: bun run build
